AWSTemplateFormatVersion: 2010-09-09
Description: "Created deployment S3 bucket for the gym-crm-stack"

Parameters:
  DeployBucketName:
    Type: String
    Default: gym-deploy-bucket

Resources:
  DeployBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Description: "This bucket is used to store files for deployment, like java projects and lambdas"
    Properties:
      BucketName: !Ref DeployBucketName