AWSTemplateFormatVersion: 2010-09-09
Description: "Use this stack before creating the gym stack. This stack creates the s3 deploy bucket to store deployment files"

Parameters:
  DeployBucketName:
    Type: String
    Default: gym-deploy-bucket

Resources:
  DeployBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Description: "This bucket is used to store files for deployment, like java projects and lambdas"
    Properties:
      BucketName: !Ref DeployBucketName

Outputs:
  GymDeployBucketName:
    Description: Name of the deploy bucket for the gym stack
    Value: !Ref DeployBucket

  GymDeployBucketArn:
    Description: Arn of the gym deploy bucket
    Value: !GetAtt DeployBucket.Arn
    Export:
      Name: GymDeployBucketArn