AWSTemplateFormatVersion: 2010-09-09
Description: Gym cloud template
Resources:
  GymCrmDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: "mysql"
      EngineVersion: 8.0
      DBInstanceIdentifier: java-bootcamp-gym
      MasterUsername: SuperUsernameGym
      MasterUserPassword: a3VtUsTTJ4WKq4UHEutE
      AllocatedStorage: 20
      StorageType: gp2
      DBInstanceClass: db.t2.micro
      NetworkType: ipv4
      #      DBSubnetGroupName: DbSecurityGroup
      #      VPCSecurityGroups:
      #        - DbSecurityGroup
      PubliclyAccessible: true
      Port: 3306
    #    DependsOn: DbSecurityGroup
    Description: Database instance for the GYM CRM, manage users, trainers, trainees, trainings, and security related data (like JWTs and login attempts)
    DeletionPolicy: Delete

  #  DbSecurityGroup:
  #    Type: AWS::EC2::SecurityGroup
  #    Properties:
  #      GroupDescription: "Ingress for Db instance security group"
  #      SecurityGroupIngress:
  #        - IpProtocol: tcp
  #          FromPort: 3306
  #          ToPort: 3306
  #          CIDRIP: "177.255.52.182/32" # my home ip, yay
  #        - IpProtocol: tcp
  #          FromPort: 3306
  #          ToPort: 3306
  #    DeletionPolicy: Delete

  ReportDb:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: TrainingSummary
      AttributeDefinitions:
        - AttributeName: trainerUsername
          AttributeType: S
      KeySchema:
        - AttributeName: trainerUsername
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
    DeletionPolicy: Retain
    Description: DynamoDb table to store training's information
  MessageQueue:
    Type: AWS::SQS::Queue
    Properties:
      FifoQueue: true
    DeletionPolicy: Retain