AWSTemplateFormatVersion: 2010-09-09
Description: Gym cloud template

Parameters:
  MyIpAddress:
    Type: String
    Default: 0.0.0.0/32   # 177.255.52.182/32
    Description: My IP address
  DbInstanceIdentifier:
    Type: String
    Default: gym-crm-db
  DbName:
    Type: String
    Default: gym
  DbMasterUsername:
    Type: String
    Default: SuperUsernameGym
  DbMasterPassword:
    Type: String
    Default: a3VtUsTTJ4WKq4UHEutE
  SqsFIFOQueueName:
    Type: String
    Default: gym-reporting-service-queue.fifo
    Description: "Name of the Simple Queue Service"
  ReportsBucketName:
    Type: String
    Default: gym-reports-bucket
  DeployBucketName:
    Type: String
    Default: gym-deploy-bucket
  CidrBlock:
    Type: String
    Default: 192.168.24.0/24
    Description: "The CIDR block for the VPC"
  Subnet1:
    Type: String
    Default: 192.168.24.0/25
  Subnet2:
    Type: String
    Default: 192.168.24.128/25
  VpcName:
    Type: String
    Default: gym-vpc

Resources:
  GymCrmDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: "mysql"
      EngineVersion: 8.0
      DBInstanceIdentifier: !Ref DbInstanceIdentifier
      DBName: !Ref DbName
      MasterUsername: !Ref DbMasterUsername
      MasterUserPassword: !Ref DbMasterPassword
      AllocatedStorage: 20
      StorageType: gp2
      DBInstanceClass: db.t2.micro
      NetworkType: ipv4
      PubliclyAccessible: true
      Port: 3306
      DBSubnetGroupName:
        Ref: GymSubnetGroup
      VPCSecurityGroups:
        - !Ref DBSecurityGroup
        - !Ref MyEC2SecurityGroup
    Description: "Database instance for the GYM CRM, manage users, trainers, trainees, trainings, and security related data (like JWTs and login attempts)"
    DeletionPolicy: Delete
  ReportDb:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: TrainingSummary
      AttributeDefinitions:
        - AttributeName: trainerUsername
          AttributeType: S
      KeySchema:
        - AttributeName: trainerUsername
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
    DeletionPolicy: Delete
    Description: DynamoDb table to store training's information
  MessageQueue:
    Type: AWS::SQS::Queue
    Properties:
      FifoQueue: true
      QueueName:
        Ref: SqsFIFOQueueName
    DeletionPolicy: Delete

  # Buckets
#  DeployBucket:
#    Type: AWS::S3::Bucket
#    DeletionPolicy: Delete
#    Description: "This bucket is used to store files for deployment, like java projects and lambdas"
#    Properties:
#      BucketName: !Ref DeployBucketName

  ReportsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Description: "Bucket to store the reports"
    Properties:
      BucketName: !Ref ReportsBucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
  MyBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Description: "This policy allows public read access to the bucket"
    Properties:
      Bucket:
        Ref: ReportsBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource:
              Fn::Join:
                - ''
                - - 'arn:aws:s3:::'
                  - Ref: ReportsBucket
                  - '/*'

  # Security, Subnets, routing and VPC
  DBSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Security group for RDS. Allow only access from a IP address, or CIDR range.'
      VpcId: !Ref GymVPC
      SecurityGroupIngress:
        - CidrIp: !Ref MyIpAddress
          IpProtocol: 'tcp'
          FromPort: '3306'
          ToPort: '3306'
      SecurityGroupEgress:
        - CidrIp: !Ref MyIpAddress
          IpProtocol: 'tcp'
          FromPort: '3306'
          ToPort: '3306'
    DeletionPolicy: Delete

  MyEC2SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Security group for EC2 instances to access RDS'
      VpcId: !Ref GymVPC
      SecurityGroupIngress:
        - SourceSecurityGroupId: !GetAtt DBSecurityGroup.GroupId  # Allow access from the RDS security group. Resources associated with this DBSecurityGroup can access MyEC2SecurityGroup
          IpProtocol: 'tcp'
          FromPort: '3306'
          ToPort: '3306'
    DeletionPolicy: Delete

  GymVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref CidrBlock
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Ref VpcName
    DeletionPolicy: Delete
  GymSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref GymVPC
      CidrBlock: !Ref Subnet1
      AvailabilityZone: "us-east-1a"
    DeletionPolicy: Delete
  GymSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref GymVPC
      CidrBlock: !Ref Subnet2
      AvailabilityZone: "us-east-1b"
    DeletionPolicy: Delete
  GymSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "Gym CRM subnet group"
      SubnetIds:
        - Ref: GymSubnet1
        - Ref: GymSubnet2
    DeletionPolicy: Delete
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: MyInternetGateway
    DeletionPolicy: Delete
  VpcGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref GymVPC
      InternetGatewayId: !Ref InternetGateway
    DeletionPolicy: Delete
  MyRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref GymVPC
      Tags:
        - Key: Name
          Value: MyRouteTable
    DeletionPolicy: Delete
  MyRoute:
    Type: AWS::EC2::Route
    DependsOn: VpcGatewayAttachment
    Properties:
      RouteTableId: !Ref MyRouteTable
      DestinationCidrBlock: '0.0.0.0/0'
      GatewayId: !Ref InternetGateway
    DeletionPolicy: Delete

  MySubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref GymSubnet1
      RouteTableId: !Ref MyRouteTable
    DeletionPolicy: Delete

  MySubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref GymSubnet2
      RouteTableId: !Ref MyRouteTable
    DeletionPolicy: Delete

Outputs:
  DbInstanceEndpoint:
    Description: "Endpoint of the RDS instance"
    Value: !GetAtt GymCrmDatabase.Endpoint.Address

  ReportsBucketEndpoint:
    Description: "URL for the Reports S3 bucket"
    Value: !GetAtt ReportsBucket.WebsiteURL