#####################################################
####### Configuration file for using with aws #######
###-----------------------------------------------###
### MYSQL Database, DynamoDB and SQS -------------###
#####################################################

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://gym-crm-db.cwzsp1bit6fj.us-east-1.rds.amazonaws.com:3306/gym
    username: SuperUsernameGym
    password: a3VtUsTTJ4WKq4UHEutE
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: false
        format_sql: false
  config:
    import: "optional:configserver:"
  cloud:
    discovery:
      enabled: false

cloud:
  aws:
    region:
      auto: false
      static: us-east-1
    sqs:
      endpoint: https://sqs.us-east-1.amazonaws.com/208668734131/gym-reporting-service-queue.fifo
      queue-name: gym-reporting-service-queue.fifo

security:
  jwt:
    secret: "ThisIsTheSecretUsedToCreateTheJWTTokenButItNeedsToBeVeryLong"

logging:
  level:
    root: debug