logging:
  level:
    root: info

data:
  mock:
    user: "mock_data\\user.csv"
    training_type: "mock_data\\training.csv"
    trainee: "mock_data\\trainee.csv"
    trainer: "mock_data\\trainer.csv"
    training: "mock_data\\training.csv"

spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost;databaseName=gym_crm;Trusted_Connection=True;TrustServerCertificate=true;
    username: gym_admin
    password: gym_administrator


