##################################################################
######### Configuration file for local development ###############
###------------------------------------------------------------###
### Database is SQL Server, localhost instance ----------------###
###------------------------------------------------------------###
### Configuration server is optional, must specify host -------###
###------------------------------------------------------------###
### Disables Discovery Service---------------------------------###
##################################################################

# hibernate configuration
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost;databaseName=gym_crm;Trusted_Connection=True;TrustServerCertificate=true;
    username: gym_admin
    password: gym_administrator
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        show_sql: true
        format_sql: true
  config:
    import: "optional:configserver:"
  cloud:
    discovery:
      enabled: false

# health checks - actuator
management:
  endpoint:
    health:
      enabled: true
      show-details: always
    loggers:
      enabled: true
    prometheus:
      enabled: true
    info:
      enabled: true
  endpoints:
    jmx:
      exposure:
        include: "health"
    web:
      exposure:
        include: "health,loggers,info,prometheus"

# Security
security:
  jwt:
    secret: "ThisIsTheSecretUsedToCreateTheJWTTokenButItNeedsToBeVeryLong"

# logging
logging:
  level:
    root: debug
