spring:
  application:
    name: gym-service

  jpa:
    hibernate:
      naming:
        physical-strategy:
    properties:
      hibernate:
        dialect:
  config:
    import: "optional:configserver:"

  artemis:
    broker-url: "tcp://localhost:61616"
#    broker-url: "tcp://artemis-server:61616"
    mode: native
    user: artemis # ${ARTEMIS_USER}
    password: artemis # ${ARTEMIS_PASSWORD}

server:
  port: 8081

logging:
  level:
    root: info
