package com.javabootcamp.gym.services;

import com.javabootcamp.gym.data.model.Trainer;
import com.javabootcamp.gym.data.model.User;
import com.javabootcamp.gym.data.repository.TrainerRepository;
import com.javabootcamp.gym.data.repository.TrainingTypeRepository;
import com.javabootcamp.gym.data.repository.UserRepository;
import com.javabootcamp.gym.services.helper.UserHelper;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.UUID;

@Service
public class TrainerService {
    private final Logger logger = LoggerFactory.getLogger(TrainerService.class);
    private final TrainerRepository trainerRepository;
    private final UserRepository userRepository;
    private final TrainingTypeRepository trainingTypeRepository;

    @Autowired
    public TrainerService(@NotNull TrainerRepository trainerRepository, @NotNull UserRepository userRepository, TrainingTypeRepository trainingTypeRepository) {
        this.trainerRepository = trainerRepository;
        this.userRepository = userRepository;
        this.trainingTypeRepository = trainingTypeRepository;
    }

    /**
     * Creates a new Trainer
     *
     * @param userId           The {@link User} id
     * @param specializationId The {@link com.javabootcamp.gym.data.model.TrainingType} id
     * @return A new instance of {@link Trainer} with the autogenerated properties populated,
     * or null if it couldn't be created.
     * @see User
     */
    @Nullable
    public Trainer create(int userId, int specializationId) {
        logger.trace("create: userId={}, specializationId={}", userId, specializationId);
        if (userId <= 0 || specializationId <= 0) {
            logger.trace("Invalid id(s)");
            return null;
        }

        var user = userRepository.findById(userId);

        if (user.isEmpty()) {
            logger.trace("create: user ({}) not found", userId);
            return null;
        }

        var trainingType = trainingTypeRepository.findById(specializationId);
        if (trainingType.isEmpty()) {
            logger.trace("create: training type ({}) not found", specializationId);
            return null;
        }
        logger.info("Creating trainer");

        var trainer = new Trainer(trainingType.get(), user.get());

        return trainerRepository.save(trainer);
    }

//    /**
//     * Create a new User and a Trainer with the User id
//     *
//     * @param firstName        The User firstname
//     * @param lastName         The User lastname
//     * @param specializationId the Trainer Specialization id
//     * @return A new instance of {@link Trainer} with autogenerated properties populated, including the userId
//     * or null if it couldn't be created.
//     * @see User
//     * @see com.javabootcamp.gym.data.model.TrainingType
//     */
//    @Nullable
//    public Trainer create(@NotNull String firstName, @NotNull String lastName, int specializationId) {
//        logger.trace("create: firstName='{}', lastName='{}', specializationId={}", firstName, lastName, specializationId);
//
//        if (specializationId <= 0)
//            return null;
//
//        var specialization = trainingTypeRepository.findById(specializationId);
//        if (specialization.isEmpty())
//            return null;
//
//        var username = UserHelper.createUsernamePrefix(firstName, lastName);
//
//        logger.trace("create: username prefix '{}'", username);
//
//        var count = userRepository.countUserByUsernameStartingWith(username);
//        logger.trace("create: username count: {}", count);
//
//        var user = UserHelper.createUser(firstName, lastName, username, count);
//
//        logger.trace("create: username='{}', password='{}'", user.getUsername(), user.getPassword());
//
//        user = userRepository.save(user);
//        logger.info("create: created user");
//
//        return trainerRepository.save(new Trainer(specializationId, user));
//    }

    @Nullable
    public Trainer getById(int id) {
        logger.trace("getById: id={}", id);
        if (id <= 0) return null;

        logger.info("Retrieving training");

        return trainerRepository.getById(id);
    }

//    boolean update(@NotNull Trainer trainer) {
//        logger.trace("update: updating user id={}", trainer.getId());
//        if (trainer.getId() <= 0) {
//            logger.trace("update: invalid id");
//            return false;
//        }
//        return trainerRepository.update(trainer);
//    }
}
