spring:
  application:
    name: reporting-service

#  config:
#    import: "configserver:http://localhost:8888"
  #  cloud:
  #    config:
  #      username: <username>
  #      password: <password>
server:
  port: 8082

logging:
  level:
    root: info


# Its okay, these credentials do not exist
#cloud:
#  aws:
#    credentials:
#      access-key: "AKIATBFNAGKZ44IUD75D"
#      secret-key: "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"
#    region:
#      auto: false
#      static: us-east-1
#    sqs:
#      endpoint: sqs-endpoint
#      queue-name: queue-name

