spring:
  application:
    name: reporting-service
  config:
    import: "optional:configserver:"
  cloud:
    discovery:
      enabled: false

  artemis:
    #    broker-url: "tcp://localhost:61616"
    #    broker-url: "tcp://artemis-server:61616"
    broker-url: "tcp://gym-artemis-container-compose:61616"
    mode: native
    user: artemis # ${ARTEMIS_USER}
    password: artemis # ${ARTEMIS_PASSWORD}

server:
  port: 8082

logging:
  level:
    root: info
